### PR TITLE
Fix EdDsaSAPublicKeySecp256k1 example.

### PR DESCRIPTION
**Pull request by peacekeeper**

### CODE REVIEW

**Comment by mikelodder7** [comment]
Secp256K1 doesn't do EdDsa. It does ECDSA. There is an important crypto difference between the two. The name should be ECDSAPublicKeySecp256k1.

**Comment by peacekeeper** [comment]
I'm aware of this. This PR is just to align the example title with the example itself. I suggest discussing the details of the Cryptographic Suite elsewhere.

**Comment by mikelodder7** [comment]
Do you know where to discuss?

**Comment by msporny** [comment]
@mikelodder7 wrote:
> Do you know where to discuss?

I suggest here:

https://github.com/w3c-dvcg/lds-koblitz2016

Spec available here:

https://w3c-dvcg.github.io/lds-koblitz2016/

... although, I note the signature type is already `EcdsaKoblitzSignature2016`.

That specification should also define the key types, which could be:

`EcdsaKoblitzVerificationKey2016`

... in any case, I suggest bringing it up in the lds-koblitz2016 repository (which is crazy old and outdated)... we really need to use a general template for all these cryptosuite specs.

**Comment by ChristopherA** [comment]
Now that Peter Wuille’s formalization of Schnorr is out, I’m hoping to have us have a spec for Secp256k1SchnorrSignature2018.

**Comment by peacekeeper** [comment]
Replaced by https://github.com/w3c-ccg/ld-cryptosuite-registry/pull/12. Closing.

**Pull request closed without merging**
