### PR TITLE
JCS Ed25519 Signature 2020 Suite

### PR DESCRIPTION
**Pull request by thereisnogabe**
Hosted on the DIF: https://identity.foundation/JcsEd25519Signature2020/

### CODE REVIEW

**Comment by OR13** [comment]
This entry looks correct, but I think we need to wait for confirmation that the go, java, and javascript implementations are functioning the same.

And I need to take another pass at reviewing the spec.

**Review by OR13 — CHANGES_REQUESTED** [review]
We have. more work to do on the spec before this is merged, and the name is likely to be changed.

**Comment by thereisnogabe** [comment]
Updated name

**Review by OR13 — APPROVED** [review]
Its a bit odd to add a suite that doesn't support JSON-LD to a Linked Data Crypto Suite Registry, but it might be helpful for others.

**Comment by OR13** [comment]
@msporny @talltree can you give your thoughts on this?

**Comment by msporny** [comment]
> Its a bit odd to add a suite that doesn't support JSON-LD to a Linked Data Crypto Suite Registry, but it might be helpful for others.

In the early days, I specifically pushed JSON-LD in the direction of rejecting RDF due to it's complexity and, what I viewed to be, a hard headed, uncompromising community of academics. In time, the RDF and JSON-LD communities came together.

http://manu.sporny.org/2014/json-ld-origins-2/

BUT... the Linked Data part of JSON-LD was specifically not RDF. We didn't call it JSON-RDF on purpose, because we didn't want to assert that RDF was the only way to do Linked Data (because, initially, JSON-LD wasn't based on RDF at all).

So, I suggest throwing up the horns :smiling_imp: and merging this :fire: :apple: :shopping_cart: :fire:. Yes, you can only generate the signature in a JSON syntax, but that's not wrong.

**Pull request merged**
